$schema: https://moonrepo.dev/schemas/project.json
tasks:
  build:
    outputs: []
    deps:
    - ts-config-base:build
    - ^:build
language: other
tags:
- tenant-shared
- tsconfig
dependsOn: []
fileGroups:
  sources:
  - src/**/*
  tests:
  - src/**/*.test.*
  - src/**/*.spec.*
  - test/**/*
  configs:
  - '*.config.*'
  - tsconfig*.json
  - .eslintrc*
  - .prettierrc*
  - package.json
layer: configuration
