$schema: https://moonrepo.dev/schemas/tasks.json
extends: ./tag-typescript.yml
tasks:
  build:
    deps: []
    options:
      mergeDeps: replace
  test:
    deps: []
    options:
      mergeDeps: replace
  test-watch:
    deps: []
    options:
      mergeDeps: replace
  lint:
    deps:
      - build
    options:
      mergeDeps: replace
  lint-fix:
    deps:
      - build
    options:
      mergeDeps: replace
  typecheck:
    deps:
      - build
    options:
      mergeDeps: replace
  coverage:
    deps: []
    options:
      mergeDeps: replace
inheritedBy:
  tag: typescript-script
