$schema: https://moonrepo.dev/schemas/tasks.json
inheritedBy:
  tag: docker
fileGroups:
  dockerfiles:
    - Dockerfile
    - Dockerfile*
    - docker/**/Dockerfile*
tasks:
  docker-lint:
    command:
      - hadolint
      - Dockerfile
    inputs:
      - '@globs(dockerfiles)'
    outputs: []
    options:
      cache: true
