$schema: https://moonrepo.dev/schemas/project.json
language: typescript
layer: configuration
tags:
  - npm
  - tenant-shared
  - typescript-config
dependsOn:
  - eslint-config-base
  - ts-config-build
