$schema: https://moonrepo.dev/schemas/project.json
language: typescript
layer: configuration
tags:
  - npm
  - tenant-shared
  - typescript
dependsOn:
- vitest-config-base
- eslint-config-base
- ts-config-build
